services:
  tg_bot_crawler:
    build: .
    command: python bot.py
    depends_on:
      - redis
      - celery_worker
    volumes:
      - ./:/app

  flask_server:
    build: .
    command: python server.py
    ports:
    - 5000:5000
    volumes:
      - ./:/app

  celery_worker:
    build: .
    command: celery -A tasks worker -B --loglevel=INFO -c 10 -f celery_tasks_logs.log
    volumes:
      - ./:/app
    depends_on:
      - redis

  redis:
    image: redis:latest

    ports:
    - 6379:6379
    # expose:
    #   - "6379"